### ISSUE TITLE
Add branches lesson

### ISSUE THREAD

**Issue by sstevens2** [UW-Madison-ACI/20170830-git-novice#1]

**Comment by sstevens2** [comment]
Working on this.  I'm going to add the lesson based on [notes from here](http://sarahlrstevens.info/2017-08-02-chicago-frb/extras/2017-08-03-git_motivation.pdf).  I'll be adding it like I had in my notes where we make a `pythondev` branch and a `bashdev` branch but we only `touch` the scripts and then add and commit them.  I've almost got it together but if you want to improve it to coordinate better with the bash session that would be great.

**Comment by pshriwise** [comment]
Sounds like a great plan, thank you!

**Comment by pshriwise** [comment]
This was addressed in #5
