### ISSUE TITLE
Modify conflicts lesson

### ISSUE THREAD

**Issue by sstevens2** [UW-Madison-ACI/20170830-git-novice#2]

**Comment by sstevens2** [comment]
@pshriwise Do you think that doing the conflicts with the branching is a good idea?  
I've been hoping it would save some time since it is an easier conflict but I'm now worried that it is too fake of an example.  Maybe we can think of a story where a conflict in branches would make sense?  
Maybe we should have the practice by ending the PR lesson by pulling in a conflict from the upstream countries (e.g. everyone adds their country to a list of counties and they pull in the instructors version which conflicts)?

**Comment by pshriwise** [comment]
I like the idea of doing conflicts with branching a lot the more I think about it. I think that if we work with the person teaching the bash session - we could modify the code in two different ways, in two different branches and merge them. 

I think that doing the branches and conflicts completely locally without going to GitHub might remove a layer of confusion from branching and make it clear that conflicts aren't something you'll run into just as a result of collaborating with others. What do you think?

**Comment by pshriwise** [comment]
Proposed lesson scheme if we go that route:
  - branching demo using bash script
  - handling conflicts
  - GitHub and collaborating via Pull Requests

**Comment by sstevens2** [comment]
Sounds like what I was thinking!  I do like conflicts better in local branches as it is a more controlled conflict which is both quicker and less confusing.  My biggest worry was that if you are working by yourself you might be less likely to encounter a conflict which would make it sort of artificial.  But I think with a good story we can make it work.   Though if possible I think we should challenge them with a conflict at the end of the PR (See note in issue #3).  Sorry these comments are getting confusing since they are all kind of related 🤷‍♀️

**Comment by sstevens2** [comment]
@pshriwise Let me know if you want me to draft moving the conflict lesson up and having it in branches or you would like to do it!

**Comment by pshriwise** [comment]
Conflict at the end of the PR exercise - yes! I was thinking about that too. Then they can experience it in two ways. 

@sstevens2 I'm happy to take care of the conflict lesson. Feeling like I need to take on some more here :smile: I'll try to work on that tomorrow morning, but my afternoon is pretty swamped.

**Comment by sstevens2** [comment]
No rush!  I'm just a bit excited about trying this out and so wanted to help.  Since you are teaching though I don't want to step on your toes and do too much. I'll leave you conflicts and work on getting the branches out of the PR lesson, if you are alright with that.

**Comment by sstevens2** [comment]
@pshriwise Let me know if you want to add the branching conflicts lesson and remove old conflicts or if I should?

**Comment by pshriwise** [comment]
I have a branch almost ready for this. It just needs a few small adjustments before I PR. Hopefully I can get to that tomorrow morning?

**Comment by sstevens2** [comment]
Sure. Great!
Sarah
