### ISSUE TITLE
Replace current collaboration with PR lesson

### ISSUE THREAD

**Issue by sstevens2** [UW-Madison-ACI/20170830-git-novice#3]

**Comment by pshriwise** [comment]
Best way to do this? 

I'm thinking the best way is for one of us to force push to replace the `gh-pages` branch (or a some other branch name if we want) with your modified lesson (https://github.com/sstevens2/git-novice-mod) and go from there. 

There's also the matter of what to do with all of the other branches in this repository right now...

**Comment by sstevens2** [comment]
@pshriwise  I made PR #4 with the pull request lesson instead of the collaborating lesson.  Still need some work but could you take a look at it and merge it for a start if it looks okay?

As for the branches...I propose deleting all of the other branches? Maybe @ChristinaLK could switch the default branch to `gh-pages` in settings (sorry for all of the admin requests!).

**Comment by sstevens2** [comment]
@pshriwise Now I'm realizing that you maybe meant doing something with branches to get the PR lesson in??  Is this solution okay?

**Comment by ChristinaLK** [comment]
I didn't realize gh-pages wasn't the default.  Will change.

**Comment by sstevens2** [comment]
Thanks @ChristinaLK !

**Comment by pshriwise** [comment]
Awesome @sstevens2! I'll take at #4 look today. 

WRT the other branches. Yeah, I think we should delete them.

**Comment by pshriwise** [comment]
@sstevens2 Yeah I think this will work just fine!

I didn't know if these changes would contain a lot of conflicts given that we don't know its history, so I thought replacing it might be the best option to start. It seems as though your PR can be merged cleanly though so that's definitely the way to go 😄

**Comment by sstevens2** [comment]
New issue? I was thinking at the end of the PR lesson, we could have them update their branch from `upstream` but first everyone add their country to a file containing the list of countries but the same line (and add and commit).  Then they try to update their branches from the `upstream` one and they get the instructor's country conflicting with theirs.
