### ISSUE TITLE
Remove/Fix branching in PR lesson

### ISSUE THREAD

**Issue by sstevens2** [UW-Madison-ACI/20170830-git-novice#7]

**Comment by pshriwise** [comment]
I commented on this in #5  before reading this, so please disregard that comment. :clock1:

**Comment by sstevens2** [comment]
We need to have an org host the countries repo.  We could make a make org to host 'countries' or have Christina/Lauren setup this repo.
I have a version I setup and used for mine that we could reset and work from.  Or we could make an empty repo with just a `Readme` and add from there.

**Comment by sstevens2** [comment]
Closed but realized we still need to setup the authoritative version so reopened
